---
kind: pipeline
type: kubernetes
name: Build

steps:
  - name: Build and Publish Image
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO,,}
      tags:
        - ${DRONE_SOURCE_BRANCH/\//-}
        - ${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
      cache_from:
        - ${DRONE_REPO,,}:${DRONE_SOURCE_BRANCH/\//-}
      username: estudosdevops
        # from_secret: DOCKER_USERNAME
      password: estudosdevops@123
        # from_secret: DOCKER_PASSWORD
    when:
      event:
        exclude:
          - tag
