kind: pipeline
type: kubernetes
name: default

steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    repo: estudosdevops/node
    registry: docker.io
    username:
        from_secret: docker-username
    password:
        from_secret: docker-password
